apiVersion: v1
kind: Service
metadata:
  name: bookstore
spec:
  type: NodePort
  selector:
    app: bookstore-demo
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-demo
spec:
  selector:
    matchLabels:
      app: bookstore-demo
  template:
    metadata:
      labels:
        app: bookstore-demo
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: bookstore-demo
        image: bookstore-demo:2.4.4
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: bookstore-config
        readinessProbe:
          httpGet:
            port: 7777
            path: /_ping
        ports:
        - containerPort: 8080
